---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-permissions
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - configmaps
  - services
  - routes
  - pods
  - namespaces
  - projects
  - mcpservers
  verbs:
  - get
  - list
  - watch